overrides:
  hono: 4.12.25
  '@hono/node-server': 1.19.10
  effect: 3.20.0
  lodash: 4.18.1
  defu: 6.1.5

allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - prisma
