apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-challenge
type: Opaque
stringData:
  POSTGRES_DB: currencies
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: replace-with-a-secure-password
  POSTGRES_PRISMA_URL: postgres://postgres:postgres@postgres.devops-challenge.svc.cluster.local:5432/currencies?schema=public
