apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-challenge
resources:
  - ../../base
  - secret.yaml
images:
  - name: ghcr.io/moonpay/devops-challenge
    newName: ghcr.io/moonpay/devops-challenge
    newTag: latest
  - name: ghcr.io/moonpay/devops-challenge-migrate
    newName: ghcr.io/moonpay/devops-challenge-migrate
    newTag: latest
patches:
  - target:
      kind: Ingress
      name: web
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: devops-challenge.127.0.0.1.nip.io
