apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-challenge
resources:
  - ../../base
  - sealed-secret.yaml
images:
  - name: ghcr.io/moonpay/devops-challenge
    newName: ghcr.io/jean-christopherobertson/devops-challenge
    newTag: sha-381a3367a07ab29074b175e5b6e7dae3ccb1def1
  - name: ghcr.io/moonpay/devops-challenge-migrate
    newName: ghcr.io/jean-christopherobertson/devops-challenge-migrate
    newTag: sha-381a3367a07ab29074b175e5b6e7dae3ccb1def1
patches:
  - target:
      kind: Ingress
      name: web
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: devops-challenge.127.0.0.1.nip.io
