apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-challenge
resources:
  - ../../base
  - secret.yaml
images:
  - name: ghcr.io/moonpay/devops-challenge
    newName: ghcr.io/jean-christopherobertson/devops-challenge
    newTag: sha-949033b414bb67a6b058c2432a8bcde4aaaf232f
  - name: ghcr.io/moonpay/devops-challenge-migrate
    newName: ghcr.io/jean-christopherobertson/devops-challenge-migrate
    newTag: sha-949033b414bb67a6b058c2432a8bcde4aaaf232f
patches:
  - target:
      kind: Ingress
      name: web
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: devops-challenge.127.0.0.1.nip.io
